version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: lb-postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      # run migrations on first boot
      - ./leaderboard/db/migrations:/docker-entrypoint-initdb.d
      # persist data across restarts
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10  
  
  redis:
    image: redis:7
    container_name: lb-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 1s
      timeout: 5s
      retries: 10
  
  nginx:
    image: nginx:1.27
    container_name: lb-nginx
    depends_on:
      api:
        condition: service_started
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    


  api:
    build: ./leaderboard
    container_name: lb-api
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      # IMPORTANT: talk to postgres by service name "postgres" container name, not localhost
      PG_URI: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      REDIS_ADDR: redis:6379
      PORT: "8080"
    ports:
      - "8080:8080"

volumes:
  pgdata:
